### ISSUE TITLE
Cursor flickering while moving fast

### ISSUE THREAD

**Issue by pymaldebaran** [GregoireHENRY/chart#2]
# The problem

When moving the cursor quite fast, we can see the horizontal and vertical lines that follow the cursor getting doubled.

# The suspects

This may be a double buffering not activated problem or a software rendering instead of hardware rendering.

Other possible suspect : clean :arrow_right: fill with background (missing ?) :arrow_right: draw :arrow_right: blit

# TODO list

- [ ] invertigate the SDL2 initialisation
- [ ] do some tests with different config
- [ ] find the right config and apply it cleanly
