### ISSUE TITLE
Activate static linking to SDL2 .so/.dll

### ISSUE THREAD

**Issue by pymaldebaran** [GregoireHENRY/chart#4]
# The problem

The linking to SDL2 libraries is curently dynamic thus forcing us to have the SDL2 library present on the client computer. And this leads to many distribution problems.

# Current solutions

Currently we have 2 different solutions depending on the platform:

- **windows** : we have the dll files in the repository and copy them next to the produced .exe with the `compile` script
- **linux** : we need for the client to install `libsdl2.0-dev` on it's machine in order to have the .so file available...

Both situations have problems:

- **windows** : we have an external library hosted on the repository in pure binary form, we WILL forget to update it if it has any (security) update
- **linux** : we do not even check during compilation il the lib is present ! And we shouldn't rely on non explicit dependancy

# Roadmap to solutions

- [x] **windows** remove the .dlls from the repository and modify the `compile` script to download them via `wget` from their [source repository](https://www.libsdl.org/download-2.0.php) to the destination `usr` directory.
- [x] **linux** in `compile` script check for the presence of the lib before comiling and provide a clean error message providing relevent informations on how to install `libsdl2.0-dev`
- [ ] **both** switch to real static linking and integrate the libsdl inside the executable
